#端口号
server:
  port: 8080
  servlet:
    context-path: /boot
  undertow:
    max-parameters: 104857600
    max-http-post-size: -1


spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/templates/view/,classpath:/static/

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  #  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    encoding: UTF-8


  freemarker:
    prefix: classpath:/templates/view/
    suffix: .html
    cache: false
    encoding: UTF-8

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.boot.entity

